site_name: My Docs
repo_url: https://github.com/an1shthomas/docs
edit_uri: blob/main/docs/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view

  font:
    text: Work Sans


  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode    


markdown_extensions:
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.betterem
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: timeago